language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go get -t -v ./...
  - go get -v golang.org/x/lint/golint

script:
  - golint -set_exit_status ./...
  - go test -race -coverprofile=coverage.out -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
